/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/59aUmPQu3kt
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Mono } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_mono({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
'use client'

import Image from 'next/image';
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Percent } from "lucide-react"
// lucide.dev/icons
import { useState } from 'react';
import axios from 'axios'; // Import axios for making HTTP requests
import React from 'react';

export function Landing() {
  const [email, setEmail] = useState('');

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      await axios.post('/api/saveEmail', { email });
      // Optionally, you can handle success behavior here
      console.log('Email saved successfully');
    } catch (error) {
      // Handle error
      console.error('Error saving email:', error);
    }
  };

  return (
    <>
      <div className="flex flex-col min-h-[100dvh]">
      {/* <div className="relative w-full min-h-screen bg-gradient-to-br from-[#1E1E1E] to-[#0F0F0F] dark:bg-gradient-to-br dark:from-[#0F0F0F] dark:to-[#1E1E1E]"> */}
        <header className="px-4 lg:px-6 h-14 flex items-center">
          <Link className="flex items-center justify-center" href="#">
            <PadanaIcon />
            <span className="sr-only">Padana</span>
            <span className="ml-2 text-gray-900 font-semibold">Padana</span>
          </Link>
          {/* Right bar */}
          {/* <nav className="ml-auto flex gap-4 sm:gap-6">
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
              Features
            </Link>
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
              Pricing
            </Link>
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
              About
            </Link>
            <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
              Contact
            </Link>
          </nav> */}
        </header>
        <main className="flex-1">
            <section className="w-full py-8 md:py-16 lg:py-24">
            <div className="container mx-auto px-4 md:px-6"> 
              <div className="flex flex-col items-center space-y-10 text-center">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none bg-clip-text text-transparent bg-gradient-to-r from-green-400 to-blue-500" style={{ lineHeight: "1.2" }}>
                  Supercharge Your Research with AI: ChatPharma
                </h1>
                <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400" style={{ lineHeight: "1.6" }}>
                  Streamline pharmaceutical data analysis and accelerate informed decision-making with game-changing AI for faster drug discovery.
                </p>

                <div className="w-full max-w-sm space-y-2">
                  <form onSubmit={handleSubmit} className="flex space-x-2">
                    <Input
                      className="max-w-lg flex-1"
                      placeholder="Enter your business email"
                      type="email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                    />
                    <Button
                      className="text-white hover:opacity-90 transition-opacity"
                      type="submit"
                    >
                      Join Waitlist
                    </Button>
                  </form> 
                </div>
              </div>
            </div>
            {/* <div className="w-full h-4 bg-gradient-to-r from-green-400 to-blue-500 mt-8" /> */}

          {/* <div className="relative w-full max-w-md mt-12 mx-auto">
            <div className="absolute 
            inset-0 bg-gradient-to-br from-[#6AEAFF] to-[#FF6AE6] 
            rounded-2xl blur-3xl opacity-50 animate-ripple" />
            <div className="relative z-10 bg-gray-900 rounded-2xl p-6 space-y-4 shadow-lg">
              <h2 className="text-2xl font-bold text-gray-50">Join the Waitlist</h2>
              <p className="text-gray-400">
                Be the first to experience the power of ChatPharma. Enter your email to join the waitlist.
              </p>
              <form className="space-y-4">
                <Input className="w-full" placeholder="Enter your email" type="email" />
                <Button className="w-full" type="submit">
                  Join Waitlist
                </Button>
              </form>
            </div>
          </div> */}

          </section>

          <section className="w-full py-8 md:py-16 lg:py-24 bg-gray-100 dark:bg-gray-800">
            <div className="container
            mx-auto
            grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
              <div className="space-y-6">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight bg-clip-text text-gray-900 bg-gray-100 dark:text-gray-900">
                  Using what works and scales
                </h2>
                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Our platform uses the latest yet proven technologies to ensure we deliver the best results.
                </p>
              </div>
              <div className="grid w-full grid-cols-2 lg:grid-cols-5 items-center justify-center gap-8 lg:gap-12 [&>img]:mx-auto">
                <Image
                  alt="OpenAI"
                  className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                  height={70}
                  src="/openai.svg"
                  width={140}
                />
                <Image
                  alt="Meta"
                  className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                  height={60}
                  src="/meta.svg"
                  width={120}
                />
                <Image
                  alt="PostgreSQL"
                  className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                  height={70}
                  src="/psql.svg"
                  width={140}
                />
                <Image
                  alt="MongoDB"
                  className="aspect-[2/1] overflow-hidden rounded-lg object-contain object-center"
                  height={70}
                  src="/mongodb.svg"
                  width={140}
                />
                <Image
                  alt="LlamaIndex"
                  className="aspect-[2/1] col-span-2 lg:col-span-1 overflow-hidden rounded-lg object-contain object-center"
                  height={70}
                  src="/llama.jpeg"
                  width={140}
                />
              </div>
            </div>
          </section>


          {/* <section className="bg-gray-100 py-12 md:py-24 lg:py-32 dark:bg-gray-800">
            <div className="container mx-auto px-4 md:px-6">
              <div className="grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
                <div className="flex flex-col justify-center space-y-4">
                  <div className="space-y-4">
                    <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                      Meet the Experts
                    </div>
                    
                    <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl bg-clip-text text-dark bg-gray-900">
                      Discover Cutting-Edge Research
                    </h2>
                    <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                      Gain personalized access to a diverse range of experts, including leading drug researchers, and
                      get insights into the latest advancements in the field.
                    </p>
                  </div>
                  <ul className="grid gap-2 py-4">
                    <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Connect with drug research experts
                    </li>
                    <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Learn about the latest breakthroughs
                    </li>
                    <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Ask questions and get personalized insights
                    </li>
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Expand your knowledge in the field of drug research
                    </li>
                  </ul>
                  <div className="flex flex-col gap-2 min-[400px]:flex-row">
                    <Link
                      className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm 
                      font-medium text-gray-50 shadow transition-colors hover:opacity-90 focus-visible:outline-none 
                      focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50"
                      href="#"
                    >
                      Join Waitlist
                    </Link>
                    <Link
                      className="inline-flex h-10 items-center justify-center rounded-md 
                      border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors 
                      hover:bg-gray-100 hover:text-gray-900 
                      focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none 
                      disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 
                      dark:focus-visible:ring-gray-300 dark:border-gray-800"
                      href="#"
                    >
                      Learn More
                    </Link>
                  </div>
                </div>
                <img
                  alt="Drug Researcher"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
              </div>
            </div>
          </section> */}

          {/* <section className="bg-gray-100 py-12 md:py-24 lg:py-32 dark:bg-gray-800">
            <div className="container mx-auto px-4 md:px-6">
              <div className="grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
                <div className="flex flex-col justify-center space-y-4">
                  <div className="space-y-4">
                    <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                      Key Features
                    </div>
                    <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl bg-clip-text text-dark bg-gray-900">
                      Elevate Your Knowledge
                    </h2>
                    <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                      Gain personalized access to a diverse range of experts across various domains. Ask questions, get
                      insights, and elevate your knowledge.
                    </p>
                  </div>
                  <ul className="grid gap-2 py-4">
                    <li>
                      <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Ask questions to get expert insights
                    </li>
                    <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Access diverse expertise across domains
                    </li>
                    <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Personalize your experience with specific experts
                    </li>
                    <li>
                    <CheckIcon className="mr-2 inline-block h-4 w-4" />
                      Tools and services for podcasters
                    </li>
                  </ul>
                  <div className="flex flex-col gap-2 min-[400px]:flex-row">
                    <Link
                    // let's make it a dark button 
                      className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:opacity-90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50"
                      href="#"
                    >
                      Join Waitlist
                    </Link>
                    <Link
                      className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                      href="#"
                    >
                      Learn More
                    </Link>
                  </div>
                </div>
                <img
                  alt="Expert Platform"
                  className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
                  height="310"
                  src="/placeholder.svg"
                  width="550"
                />
              </div>
            </div>
          </section> */}

          <section className="py-8 md:py-16 lg:py-24 mx-auto max-w-6xl">
            <div className="container px-4 md:px-6">
              <div className="space-y-4">
                <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                  Comparison</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
                  How We Stack Up Against the Competition
                </h2>
                <p className="text-gray-500 md:text-xl dark:text-gray-400">
                  See how ChatPharma stands out when it comes to answering Pharmaceutical questions.
                </p>
              </div>
              <div className="mt-8 overflow-x-auto">
              <table className="w-full table-auto text-left">
                <thead>
                  <tr className="bg-gray-100 dark:bg-gray-800">
                    <th className="px-4 py-2 font-medium">
                      Metric
                      <Percent className="h-4 w-4 inline-block ml-1 text-gray-500 dark:text-gray-400" />
                      </th>
                    <th className="px-4 py-2 font-medium">
                      Correct Info
                      <CorrectIcon className="h-4 w-4 inline-block ml-1 text-green-500 dark:text-green-400" />
                    </th>
                    <th className="px-4 py-2 font-medium">
                      Correct Tone
                      <MegaphoneIcon className="h-4 w-4 inline-block ml-1 text-green-500 dark:text-green-400" />
                    </th>
                    <th className="px-4 py-2 font-medium">
                      Relevancy*
                      <MountainIcon className="h-4 w-4 inline-block ml-1 text-green-500 dark:text-green-400" />
                      </th>
                  </tr>
                </thead>
                <tbody>
                  <tr className="border-b text-gray-900 dark:text-gray-100">
                    <td className="px-4 py-2 font-medium">ChatPharma</td>
                    <td className="px-4 py-2">85±8</td>
                    <td className="px-4 py-2">93±3</td>
                    <td className="px-4 py-2">94±3</td>
                  </tr>
                  <tr className="border-b text-gray-900 dark:text-gray-100">
                    <td className="px-4 py-2 font-medium">Meta Llama3</td>
                    <td className="px-4 py-2">59±8</td>
                    <td className="px-4 py-2">67±3</td>
                    <td className="px-4 py-2">96±3</td>
                  </tr>
                  <tr className="border-b text-gray-900 dark:text-gray-100">
                    <td className="px-4 py-2 font-medium">ChatGPT 4</td>
                    <td className="px-4 py-2">38±8</td>
                    <td className="px-4 py-2">77±3</td>
                    <td className="px-4 py-2">96±3</td>
                  </tr>
                  <tr className="border-b text-gray-900 dark:text-gray-100">
                    <td className="px-4 py-2 font-medium">ChatGPT 3.5</td>
                    <td className="px-4 py-2">35±8</td>
                    <td className="px-4 py-2">76±3</td>
                    <td className="px-4 py-2">89±3</td>
                  </tr>
                </tbody>
              </table>

              <div className="mt-8">
                <p className="text-gray-500 dark:text-gray-400">
                  * Answer Relevancy may be an indicator of hallucination.
                </p>
                </div>

              </div>
            </div>
          </section>

          {/* <section className="py-12 md:py-24 lg:py-32">
            <div className="container mx-auto px-4 md:px-6">
              <div className="mx-auto max-w-2xl">
                <div className="space-y-2">
                  <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
                    Expert Knowledge Access
                  </div>
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Unlock a Wealth of Expertise</h2>
                  <p className="text-gray-500 md:text-xl dark:text-gray-400">
                    Gain access to a vast library of curated content from industry experts, covering a wide range of
                    topics to elevate your YouTube channel, podcast, or research.
                  </p>
                </div>
                <div className="mt-8 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
                  <Card>
                    <CardHeader>
                      <VideoIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                    </CardHeader>
                    <CardContent>
                      <h3 className="text-lg font-semibold">Video Production</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        Learn from experts on camera techniques, lighting, and editing to elevate your YouTube content.
                      </p>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader>
                      <MicIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                    </CardHeader>
                    <CardContent>
                      <h3 className="text-lg font-semibold">Audio Engineering</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        Discover best practices for recording, mixing, and mastering high-quality audio for your podcast.
                      </p>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader>
                      <BookIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                    </CardHeader>
                    <CardContent>
                      <h3 className="text-lg font-semibold">Research Methodology</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        Gain insights into effective research techniques and data analysis to support your academic work.
                      </p>
                    </CardContent>
                  </Card>
                </div>
                <div className="mt-8 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
                  <Card>
                    <CardHeader>
                      <MicIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                    </CardHeader>
                    <CardContent>
                      <h3 className="text-lg font-semibold">Podcast Production</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        Learn from industry experts on how to create high-quality podcast content, from ideation to
                        post-production.
                      </p>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader>
                      <MegaphoneIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                    </CardHeader>
                    <CardContent>
                      <h3 className="text-lg font-semibold">Marketing and Promotion</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        Discover effective strategies to market and promote your podcast, reaching a wider audience.
                      </p>
                    </CardContent>
                  </Card>
                  <Card>
                    <CardHeader>
                      <DollarSignIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                    </CardHeader>
                    <CardContent>
                      <h3 className="text-lg font-semibold">Monetization</h3>
                      <p className="mt-2 text-gray-500 dark:text-gray-400">
                        Learn how to monetize your podcast through sponsorships, memberships, and other revenue streams.
                      </p>
                    </CardContent>
                  </Card>
                </div>

              </div>
            </div>
          </section> */}
          
          <section className="w-full py-8 md:py-16 lg:py-24 border-t">
            <div className="container grid mx-auto items-center justify-center gap-4 px-4 text-center md:px-6">
              <div className="space-y-6">
                <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight bg-clip-text 
                // make it dark
                text-gray-900 bg-gray-100">
                  Join the Waitlist
                </h2>

                <div className="w-full max-w-sm space-y-2">
                  <form onSubmit={handleSubmit} className="flex space-x-2">
                    <Input
                      className="max-w-lg flex-1"
                      placeholder="Enter your business email"
                      type="email"
                      value={email}
                      onChange={(e) => setEmail(e.target.value)}
                    />
                    <Button
                      className="text-white hover:opacity-90 transition-opacity"
                      type="submit"
                    > 
                      Join Waitlist
                    </Button>
                  </form>
                </div>
                
              </div>
            </div>
          </section>

        </main>
        <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
          <p className="text-xs text-gray-500 dark:text-gray-400">
            © 2024 Padana. All rights reserved.
            </p>
          <nav className="sm:ml-auto flex gap-4 sm:gap-6">
            <Link className="text-xs hover:underline underline-offset-4" href="#">
              Terms of Service
            </Link>
            <Link className="text-xs hover:underline underline-offset-4" href="#">
              Privacy
            </Link>
          </nav>
        </footer>
      </div>
      <div className="w-full h-4 bg-gradient-to-r from-green-400 to-blue-500" />
    </>
  )
}

function MegaphoneIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 11 18-5v12L3 14v-3z" />
      <path d="M11.6 16.8a3 3 0 1 1-5.8-1.6" />
    </svg>
  )
}

function MountainIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}

function CorrectIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="20 6 9 17 4 12" />
    </svg>
  )
}

function PadanaIcon() {
  return (
    <Image
      alt="Padana"
      height={24}
      width={24}
      src="/padana-logo.svg"
    />
  )
}
